# http://wiki.ros.org/base_local_planner
TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.2
  min_vel_x: 0

  max_vel_theta:  1
  min_vel_theta: -1
  min_in_place_vel_theta: 0.2

  acc_lim_x: 2
  acc_lim_theta: 3

# Goal Tolerance Parameters
  yaw_goal_tolerance: 3.14
  xy_goal_tolerance: 0.5

# Forward Simulation Parameters
  sim_time: 5
  vx_samples: 100
  vtheta_samples: 300
  sim_granularity: 0.1
# Trajectory Scoring Parameters
  meter_scoring: true
  pdist_scale: 5
  gdist_scale: 0
  occdist_scale: 30
  heading_lookahead: 4
  dwa: true
  path_distance_bias: 0
# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Differential-drive robot configuration
  holonomic_robot: false
  max_vel_y: 0.0
  min_vel_y: 0.0
  acc_lim_y: 0.0
  vy_samples: 1
