local_costmap:
   global_frame: odom
   robot_base_frame: /base_footprint
   update_frequency: 20
   publish_frequency: 20
   static_map: false
   rolling_window: true
   width: 1.5
   height: 1.5
   resolution: 0.1
   transform_tolerance: 0.1
